[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"
 
[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
cached = "0.54.0"
itertools = "0.14.0"
minilp = "0.2.2"
nom = "8"
petgraph = "0.7.0"
